# Generated by Django 4.2.23 on 2025-08-14 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='댓글내용')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.post', verbose_name='선택할 글')),
            ],
        ),
    ]
