# Generated by Django 4.2.23 on 2025-08-14 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='post', verbose_name='썸네일 이미지'),
        ),
    ]
